"""Stage D -- acceptance metrics. Writes recon/qc.yaml (PASS/FAIL per metric).

Bars are measured from 6 real ScanNet scenes (0568_00, 0019_00, 0426_00, 0217_00,
0575_02, 0304_00) -- see scannet_reference.yaml, generated by --reference.
"""
import glob
import os
import sys

import numpy as np

# --------------------------------------------------------------------------- helpers

def _read_pose(f):
    return np.loadtxt(f)


def _read_poses(pose_dir, n=None):
    files = sorted(glob.glob(os.path.join(pose_dir, "*.txt")),
                   key=lambda p: int(os.path.basename(p)[:-4]))
    if n is not None:
        files = files[:n]
    if not files:
        return np.zeros((0, 4, 4))
    return np.stack([_read_pose(f) for f in files])


def _ply_stats(path):
    """(n_vertices, n_faces, has_color, has_normal, format) from the header."""
    with open(path, "rb") as f:
        header = []
        while True:
            line = f.readline().decode("ascii", "replace").strip()
            if line == "end_header":
                break
            header.append(line)
    n_v = n_f = 0
    has_color = has_normal = False
    fmt = "ascii"
    for line in header:
        if line.startswith("format "):
            fmt = line.split()[1]
        elif line.startswith("element vertex "):
            n_v = int(line.split()[-1])
        elif line.startswith("element face "):
            n_f = int(line.split()[-1])
        elif line.startswith("property ") and "red" in line:
            has_color = True
        elif line.startswith("property ") and "nx" in line:
            has_normal = True
    return n_v, n_f, has_color, has_normal, fmt


def _load_ply(pcd_path):
    import open3d as o3d
    return o3d.io.read_point_cloud(pcd_path)


def floor_plane_stats(points):
    """(pct1_z, normal_dot_z) -- RANSAC dominant plane on the z<pct1+0.2 slab."""
    import open3d as o3d
    pct1 = float(np.percentile(points[:, 2], 1))
    slab = points[points[:, 2] < pct1 + 0.2]
    if len(slab) < 1000:
        return pct1, None
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(slab)
    _, inliers = pcd.segment_plane(distance_threshold=0.03, ransac_n=3, num_iterations=500)
    if len(inliers) < 100:
        return pct1, None
    plane = np.asarray(pcd.select_by_index(inliers).points)
    normal = np.linalg.eigh(np.cov(plane.T))[1][:, 0]
    return pct1, float(abs(normal[2]))


def _wall_azimuth_dev(mesh_path, axis_alignment):
    """Weighted histogram (2 deg bins) of horizontal wall-normal azimuths; distance of the
    dominant mode to the nearest x/y axis, after applying axisAlignment."""
    import open3d as o3d
    mesh = o3d.io.read_triangle_mesh(mesh_path)
    if not mesh.has_triangle_normals():
        mesh.compute_vertex_normals()
    V = np.asarray(mesh.vertices).copy()
    V = (V @ axis_alignment[:3, :3].T + axis_alignment[:3, 3])
    N = np.asarray(mesh.vertex_normals) @ axis_alignment[:3, :3].T
    horiz = np.abs(N[:, 2]) < 0.2
    tris = np.asarray(mesh.triangles)
    if len(tris):
        a, b, c = V[tris[:, 0]], V[tris[:, 1]], V[tris[:, 2]]
        areas = 0.5 * np.linalg.norm(np.cross(b - a, c - a), axis=1)
    else:
        areas = np.ones(len(V))
    # vertex normals -> per-triangle weight by centroid area
    w = np.zeros(len(V))
    for i, t in enumerate(tris):
        if horiz[t].any():
            w[t[horiz[t]]] += areas[i]  # rough but robust for azimuth stats
    if w.sum() == 0:
        return None
    az = np.degrees(np.arctan2(N[:, 1], N[:, 0]))
    hist, edges = np.histogram(az[w > 0], bins=180, range=(-180, 180), weights=w[w > 0])
    dom = (edges[np.argmax(hist)] + edges[np.argmax(hist) + 1]) / 2
    dev = abs(((dom + 90) % 90) - 90)
    return float(min(dev, 90 - dev))


def _backproj_residual(mesh_path, intrinsic, poses, depth_dir, color_dir, n_frames=5, depth_scale=1000.0):
    """Median nearest-neighbour distance (mm) from backprojected depth points to the mesh."""
    import open3d as o3d
    import cv2
    mesh = o3d.io.read_triangle_mesh(mesh_path)
    tree = o3d.geometry.KDTreeFlann(mesh)
    files = sorted(os.listdir(depth_dir), key=lambda p: int(p[:-4]))
    step = max(1, len(files) // (n_frames + 1))
    dists = []
    for k in files[::step][:n_frames]:
        i = int(k[:-4])
        if i >= len(poses):
            continue
        d = cv2.imread(os.path.join(depth_dir, k), cv2.IMREAD_UNCHANGED)
        if d is None or d.size == 0:
            continue
        d = d.astype(np.float32) / depth_scale
        H, W = d.shape
        fx, fy = intrinsic[0, 0], intrinsic[1, 1]
        cx, cy = intrinsic[0, 2], intrinsic[1, 2]
        yy, xx = np.mgrid[0:H, 0:W]
        m = (d > 0.1) & (d < 6.0)
        if m.sum() < 1000:
            continue
        pts = np.stack([(xx[m] - cx) * d[m] / fx, (yy[m] - cy) * d[m] / fy, d[m]], axis=1)
        pts = (pts @ poses[i][:3, :3].T + poses[i][:3, 3])
        sample = pts[:: max(1, len(pts) // 20000)]
        for p in sample:
            _, _, dist = tree.search_knn_vector_3d(p, 1)
            dists.append(dist[0])
    return float(np.median(dists) * 1000) if dists else None


def _trajectory_metrics(poses, valid_mask=None):
    n = len(poses)
    if n == 0:
        return dict(traj_length_m=0.0, revisit_pct=0.0)
    centers = poses[:, :3, 3]
    traj = float(np.linalg.norm(np.diff(centers, axis=0), axis=1).sum())
    # revisit: fraction of frames with another pose <0.5 m away >300 frames apart
    idx = np.arange(n)
    d2 = ((centers[:, None, :] - centers[None, :, :]) ** 2).sum(-1)
    mask = np.abs(idx[:, None] - idx[None, :]) > 300
    revisit = ((d2 < 0.25) & mask).sum(axis=1)
    revisit_pct = 100 * float((revisit > 0).mean())
    return dict(traj_length_m=round(traj, 2),
                revisit_pct=round(revisit_pct, 1))


# --------------------------------------------------------------------------- main

BARS = {
    "pose_valid_pct": (95.0, 100.0),
    "pose_identity_count": (0, 0),
    "vh_clean_2_verts": (120000, 250000),
    "vh_clean_2_faces": (230000, 460000),
    "verts_per_m2_floor": (4600.0, None),
    "surface_area_m2": (30.0, 80.0),
    "floor_pct1_z": (-0.10, 0.10),
    "floor_normal_dot_z": (0.999, 1.0),
    "wall_azimuth_dev_deg": (None, 2.0),
    "axis_alignment_det": (0.99999, 1.00001),
    "backproj_residual_mm": (None, 20.0),
    "frames_exported": (None, None),
    "frames_svo": (None, None),
}


def compute_metrics(scan_id: str, scan_root: str) -> dict:
    """All metrics for one scan. scan_root: /data/scannet/scans/<scan_id>."""
    recon = os.path.join(scan_root, "recon")
    frames = os.path.join(recon, "frames")
    m = {"scan": scan_id}

    # engine poses (final, ScanNet output frame) -- Stage A frames/pose are intermediates
    fin = os.path.join(recon, "final_poses.npy")
    if os.path.exists(fin):
        poses = np.load(fin)
    else:
        poses = _read_poses(os.path.join(frames, "pose"))
    m["frames_exported"] = len(poses)
    st = os.path.join(frames, "pose_state.txt")
    m["frames_svo"] = len(open(st).read().split()) if os.path.exists(st) else len(poses)
    m["pose_identity_count"] = int(np.all(np.abs(poses - np.eye(4)) < 1e-6, axis=(1, 2)).sum())
    if len(poses):
        state = os.path.join(frames, "pose_state.txt")
        if os.path.exists(state):
            toks = open(state).read().split()
            m["pose_valid_pct"] = round(100 * toks.count("OK") / len(toks), 1)
        else:
            m["pose_valid_pct"] = 100.0
        m.update(_trajectory_metrics(poses))

    clean2 = os.path.join(scan_root, f"{scan_id}_vh_clean_2.ply")
    clean = os.path.join(scan_root, f"{scan_id}_vh_clean.ply")
    if os.path.exists(clean2):
        nv, nf, col, norm, fmt = _ply_stats(clean2)
        m.update(vh_clean_2_verts=nv, vh_clean_2_faces=nf, ply_format=fmt, has_color=col, has_normals=norm)
        import open3d as o3d
        pcd = o3d.io.read_point_cloud(clean2)
        pts = np.asarray(pcd.points)
        if len(pts):
            xy = np.unique(np.round(pts[:, :2], 1), axis=0)
            from scipy.spatial import ConvexHull
            hull = ConvexHull(xy)
            m["floor_area_m2"] = round(hull.volume, 2)
            m["verts_per_m2_floor"] = round(nv / hull.volume, 0)
        p1, ndz = floor_plane_stats(pts)
        m["floor_pct1_z"] = round(p1, 3)
        if ndz is not None:
            m["floor_normal_dot_z"] = round(ndz, 4)
        if os.path.exists(clean):
            # surface area of the dense mesh (no triangle_areas in open3d 0.19)
            mesh = o3d.io.read_triangle_mesh(clean)
            V = np.asarray(mesh.vertices)
            T = np.asarray(mesh.triangles)
            if len(T):
                a, b, c = V[T[:, 0]], V[T[:, 1]], V[T[:, 2]]
                m["surface_area_m2"] = round(float(0.5 * np.linalg.norm(
                    np.cross(b - a, c - a), axis=1).sum()), 2)
    else:
        m["vh_clean_2_verts"] = m["vh_clean_2_faces"] = 0

    # axisAlignment from <id>.txt
    txt = os.path.join(scan_root, f"{scan_id}.txt")
    aa = None
    if os.path.exists(txt):
        for line in open(txt):
            parts = line.split()
            if parts and parts[0] == "axisAlignment":
                aa = np.array(list(map(float, parts[1:] if parts[1] != "=" else parts[2:]))).reshape(4, 4)
                break
    if aa is not None:
        m["axis_alignment_det"] = round(float(np.linalg.det(aa)), 6)
        m["axis_alignment_z_rot"] = bool(abs(aa[2, 2] - 1.0) < 1e-9 and abs(aa[0, 2]) < 1e-9)
        if os.path.exists(clean2):
            m["wall_azimuth_dev_deg"] = _wall_azimuth_dev(clean2, aa)

    # backprojection residual -- needs depth+poses+intrinsics
    itr = os.path.join(frames, "intrinsic_depth.txt")
    if os.path.exists(itr) and os.path.isdir(os.path.join(frames, "depth")) and len(poses) and os.path.exists(clean):
        K = np.loadtxt(itr)
        r = _backproj_residual(clean, K, poses, os.path.join(frames, "depth"),
                               os.path.join(frames, "color"))
        if r is not None:
            m["backproj_residual_mm"] = round(r, 1)

    # PASS/FAIL against bars
    out = {"metrics": m, "verdicts": {}}
    for k, (lo, hi) in BARS.items():
        if k not in m or m[k] is None:
            continue
        ok = (lo is None or m[k] >= lo) and (hi is None or m[k] <= hi)
        out["verdicts"][k] = "PASS" if ok else "FAIL"
    return out


def _write_yaml(path, data):
    import yaml

    def _plain(o):
        if isinstance(o, dict):
            return {k: _plain(v) for k, v in o.items()}
        if isinstance(o, list):
            return [_plain(v) for v in o]
        if isinstance(o, (np.floating, np.integer)):
            return o.item()
        return o

    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        yaml.safe_dump(_plain(data), f, sort_keys=False)


def run_qc(scan_id: str, scan_root: str):
    res = compute_metrics(scan_id, scan_root)
    recon = os.path.join(scan_root, "recon")
    _write_yaml(os.path.join(recon, "qc.yaml"), res)
    fails = [k for k, v in res["verdicts"].items() if v == "FAIL"]
    print(f"[qc] {scan_id}: {len(res['verdicts'])} checks, "
          f"{len(res['verdicts']) - len(fails)} PASS, {len(fails)} FAIL {fails or ''}")
    return fails


def reference(scan_dir_root: str, out_path: str):
    """Compute metrics for real ScanNet scenes; used to pin the acceptance bars."""
    import yaml
    rows = {}
    for d in sorted(os.listdir(scan_dir_root)):
        if not (d.startswith("scene0") and os.path.isdir(os.path.join(scan_dir_root, d))):
            continue
        res = compute_metrics(d, os.path.join(scan_dir_root, d))
        rows[d] = {k: v for k, v in res["metrics"].items()
                   if k in BARS and v is not None}
    with open(out_path, "w") as f:
        yaml.safe_dump(rows, f, sort_keys=False)
    print(f"[qc] reference written: {out_path} ({len(rows)} scenes)")


if __name__ == "__main__":
    mode = sys.argv[1] if len(sys.argv) > 1 else "qc"
    if mode == "--reference":
        reference("/data/scannet/scans", "/home/rolf/.local/share/opencode/worktree/"
                  "af8d5a7a5325e9bc2684882359e0eea504f05d5d/feature/reconstruction/"
                  "spellbook/reconstruct/scannet_reference.yaml")
    else:
        for sid in sys.argv[1:]:
            run_qc(sid, os.path.join("/data/scannet/scans", sid))
